[build]
builder = "RAILPACK"
installCommand = "dotnet restore TodoList/TodoList.csproj"
buildCommand = "dotnet publish TodoList/TodoList.csproj -c Release -o out --no-restore"

[deploy]
startCommand = "dotnet out/TodoList.dll"
restartPolicyType = "ON_FAILURE"